FOR REVIEW: Scopes and Frameworks
makerdao/endgame-docs pull request #89
Opened 2023-03-01 18:30 UTC by astronautthis

Staging link: https://makerdao-1.gitbook.io/endgame-docs-staging/maker-core/scopes-and-frameworks

Missing info on
1. How FaciliatatorDAOs change Frameworks
2. What Exclusive and Mandatory Scopes are

2023-03-03 15:31 UTC, LongForWisdom requested changes

2023-03-03 17:26 UTC, astronautthis commented on maker-core/scopes-and-frameworks.md
> +Certain Scopes are also tagged as Exclusive Scopes or Mandatory Scopes. The rules for Scopes with these tags has not yet been decided at the time of writing.
Leaving it for now, will update when I hear from them

2023-03-10 16:35 UTC, LongForWisdom approved these changes

2023-03-10 16:35 UTC, LongForWisdom commented on maker-core/scopes-and-frameworks.md
> +A Scope is a broad area of focus for products, protocol-related work, and/or governance in MakerDAO. All work done within the Maker Ecosystem must fall under the twelve Endgame Scopes.
```suggestion
A Scope is a broad area of focus for products, protocol-related work, and/or governance in MakerDAO. All work done within the Maker Ecosystem must fall under one of the twelve Endgame Scopes.
```

2023-03-10 16:37 UTC, merged